### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by DeMonkeyCoder** [alimahdiyar/noteif-flutter#18]
Add open-source license file and also do research about other contributors' rights.

**Comment by alifarazz** [comment]
How about GPLv3?

**Comment by DeMonkeyCoder** [comment]
@alifarazz 
I'm wondering how should we handle license for other contributors.
https://github.com/flutter/engine/blob/master/ci/licenses.sh
Also, take a look at
https://cla.developers.google.com/

**Comment by alifarazz** [comment]
Eh, we probably won't ever get big enough to need a CLA.
Though discussing anything related to CLA or contributor's agreement will need it's own issue.
I say let's sort out the project's license first. Then worry about other legal issues.

**Comment by DeMonkeyCoder** [comment]
Our purpose for handling these kinds of issues is not the project itself. We are gathering information and knowledge for future projects or probably open-source commercial projects.

**Comment by alifarazz** [comment]
So it's not related to [notif](https://github.com/alimahdiyar/noteif)?

**Comment by DeMonkeyCoder** [comment]
Why not?
It's always important to know and respect contributors' rights.
Even if it is one line of code in a simple python script.
